language: ruby
sudo: false
rvm:
  - 2.2.2
cache: bundler
branches:
  only:
    - master
before_install:
  - set -e
  - git config --global user.email "travis@incptm.com"
  - git config --global user.name "travis"
  - openssl aes-256-cbc -K $encrypted_dbf87db37731_key -iv $encrypted_dbf87db37731_iv -in id_rsa.enc -out id_rsa -d
  - mv id_rsa ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
install:
  - travis_retry bundle install
script:
  - set -e
  - rake
  - export JEKYLL_ENV=production
  - jgd -u git@github.com:incptm/website.git
